<li>
    <span class="header-questions">
        QUESTIONS? GIVE US A CALL TODAY! <a class="header-phone" href="">TEL HIER</a>
    </span>
</li>
<li><a class="header-social" href="https://www.facebook.com/Quickjacknederland/">
        <i class="fab fa-facebook"></i>
    </a>
</li>
<li><a class="header-social" href="https://www.instagram.com/quickjacknederland/">
        <i class="fab fa-instagram"></i>
    </a>
</li>
<li>
    <a class="header-social" href="https://www.twitter.com/bendpak">
        <i class="fab fa-twitter"></i>
    </a>
</li>